# Generated by Django 4.0.5 on 2022-07-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='players',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=20)),
                ('player_email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=20)),
                ('games', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
